bug fix, go-kit replace `github.com/samuel/go-zookeeper/zk` with `github.com/go-zookeeper/zk`, causing a conversion related panic
looks like nil clients are being created without tripping an error at
`service/zk/mocks_test.go` during the test `testNewEnvironmentInstancerError` (service/zk/environment_test.go)
```go
func (m *mockClientFactory) NewClient(servers []string, logger log.Logger, options ...gokitzk.Option) (gokitzk.Client, error) {
	arguments := m.Called(servers, logger, options)

	first, _ := arguments.Get(0).(gokitzk.Client)
		fmt.Printf("first: %v\narguments.Error(1): %v\narguments: %v\n", first, arguments.Error(1), arguments) // temp test output
	return first, arguments.Error(1)
}
```
produces this output
```console
first: <nil>
arguments.Error(1): <nil>
arguments: [*mock.Mock<0xc000226460> <nil>]
```
that nil client gets dereferenced during the call to `i, err = gokitzk.NewInstancer(c, path, l)` at `service/zk/environment.go`
```go
func newInstancer(l log.Logger, c gokitzk.Client, path string) (i sd.Instancer, err error) {
	fmt.Printf("%+v, %p\n", c, c)
	i, err = gokitzk.NewInstancer(c, path, l)
	if err == nil {
		i = service.NewContextualInstancer(i, map[string]interface{}{"path": path})
	}

	return
}
```
The dereference in gokitzk.NewInstancer occurs during the call to `err := s.client.CreateParentNodes(s.path)` at github.com/go-kit/kit@v0.12.0/sd/zk/instancer.go
```go
func NewInstancer(c Client, path string, logger log.Logger) (*Instancer, error) {
	s := &Instancer{
		cache:  instance.NewCache(),
		client: c,
		path:   path,
		logger: logger,
		quitc:  make(chan struct{}),
	}

	err := s.client.CreateParentNodes(s.path)
	if err != nil {
		return nil, err
	}

	instances, eventc, err := s.client.GetEntries(s.path)
	if err != nil {
		logger.Log("path", s.path, "msg", "failed to retrieve entries", "err", err)
		// other implementations continue here, but we exit because we don't know if eventc is valid
		return nil, err
	}
	logger.Log("path", s.path, "instances", len(instances))
	s.cache.Update(sd.Event{Instances: instances})

	go s.loop(eventc)

	return s, nil
}
```

Here's the dump

```
=== RUN   TestNewEnvironment/InstancerError
first: <nil>
arguments.Error(1): <nil>
arguments: [*mock.Mock<0xc000226460> <nil>]
--- FAIL: TestNewEnvironment (0.00s)
    --- PASS: TestNewEnvironment/Empty (0.00s)
    --- PASS: TestNewEnvironment/ClientError (0.00s)
    --- FAIL: TestNewEnvironment/InstancerError (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11c746b]

goroutine 38 [running]:
testing.tRunner.func1.2({0x1452120, 0x1868ee0})
        /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1212 +0x218
panic({0x1452120, 0x1868ee0})
        /usr/local/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1038 +0x215
github.com/go-kit/kit/sd/zk.NewInstancer({0x0, 0x0}, {0x14c5b5f, 0x5}, {0x155a0e0, 0xc0000a94a0})
        /Users/odc/go/pkg/mod/github.com/go-kit/kit@v0.12.0/sd/zk/instancer.go:32 +0x1ab
github.com/xmidt-org/webpa-common/v2/service/zk.newInstancer({0x155a0e0, 0xc0000a94a0}, {0x0, 0x0}, {0x14c5b5f, 0x5})
        /Users/odc/Documents/GitHub/xmidt-org/webpa-common/service/zk/environment.go:42 +0x65
github.com/xmidt-org/webpa-common/v2/service/zk.newInstancers({0x155a0e0, 0xc0000a94a0}, {0x0, 0x0}, {{{0x14cb2e7, 0x11}, {0x0, 0x0, 0x0}, 0x0, ...}, ...})
        /Users/odc/Documents/GitHub/xmidt-org/webpa-common/service/zk/environment.go:58 +0x2c5
github.com/xmidt-org/webpa-common/v2/service/zk.NewEnvironment({0x0, 0x0}, {{{0x14cb2e7, 0x11}, {0x0, 0x0, 0x0}, 0x0, 0x0}, {0x0, ...}, ...}, ...)
        /Users/odc/Documents/GitHub/xmidt-org/webpa-common/service/zk/environment.go:101 +0x16e
github.com/xmidt-org/webpa-common/v2/service/zk.testNewEnvironmentInstancerError(0xc000232b60)
        /Users/odc/Documents/GitHub/xmidt-org/webpa-common/service/zk/environment_test.go:93 +0x685
testing.tRunner(0xc000232b60, 0x14e8af8)
        /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1306 +0x35a
FAIL    github.com/xmidt-org/webpa-common/v2/service/zk 0.187s
```